config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  resources :recipes
  # Do all recipes routes individually
  #      Prefix Verb   URI Pattern                 Controller#Action
  #     recipes GET    /recipes(.:format)          recipes#index
  #             POST   /recipes(.:format)          recipes#create
  #  new_recipe GET    /recipes/new(.:format)      recipes#new
  # edit_recipe GET    /recipes/:id/edit(.:format) recipes#edit
  #      recipe GET    /recipes/:id(.:format)      recipes#show
  #             PATCH  /recipes/:id(.:format)      recipes#update
  #             PUT    /recipes/:id(.:format)      recipes#update
  #             DELETE /recipes/:id(.:format)      recipes#destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :quantities
  has_many :recipes, through: :quantities

  validates :name, presence: true
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  validates :measure, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :quantities, dependent: :destroy
  has_many :ingredients, through: :quantities
  has_many :favorite_recipes

  validates :name, :description, :difficulty, presence: true
  validates :difficulty, inclusion: { in: ["very easy", "easy", "moderate", "expert"] }
  validates :description, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :favorite_recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :difficulty)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Welcome to the most awesome recipes of the web!</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe_path(recipe) %></li>
  <% end %>
</ul>

<%= link_to "Create a new recipe", new_recipe_path, class: "btn btn-primary" %>

app/views/recipes/new.html.erb
<%= simple_form_for @recipe do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :difficulty %>
  <%= f.button :submit %>
<% end %>

app/views/recipes/show.html.erb
<h1>This is a recipe!</h1>

<p><%= @recipe.name %><p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
    <i class="fas fa-pepper-hot"></i>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>